### ISSUE TITLE
[Bug] Env var "TEMPORAL_ACTIVITY_TASK_POLLERS" documented as "TEMPORAL_WORKFLOW_ACTIVITY_TASK_POLLERS"

### ISSUE THREAD

**Issue by stephanzlatarev** [temporalio/benchmark-workers#16]
Pages https://github.com/temporalio/benchmark-workers/blob/c655d7b21f128f90b9ed7d9d7d38438ff006806f/README.md?plain=1#L44 and https://github.com/temporalio/benchmark-workers/blob/c655d7b21f128f90b9ed7d9d7d38438ff006806f/deployment.yaml#L33 document environment variable "TEMPORAL_WORKFLOW_ACTIVITY_TASK_POLLERS" but the code at https://github.com/temporalio/benchmark-workers/blob/c655d7b21f128f90b9ed7d9d7d38438ff006806f/cmd/worker/main.go#L91 looks for "TEMPORAL_ACTIVITY_TASK_POLLERS". It looks like a typo mistake.

**Comment by robholland** [comment]
Thanks for reporting!
