### ISSUE TITLE
[Feature Request] Support mTLS

### ISSUE THREAD

**Issue by richstokes** [temporalio/benchmark-workers#6]
Currently there is no way to use certificates to auth against the temporal cluster with this tool. 

Please can we add the ability to do so?

**Comment by robholland** [comment]
I've added basic support now via `TEMPORAL_TLS_CERT` and `TEMPORAL_TLS_KEY` environment variables. Please let me know if this is enough for your use case.

**Comment by richstokes** [comment]
Hmm. Normally I have to set three certs, like

export TEMPORAL_CLI_TLS_CERT=cluster.pem
export TEMPORAL_CLI_TLS_KEY=cluster.key
export TEMPORAL_CLI_TLS_CA=ca.cert

**Comment by robholland** [comment]
Updated. For `benchmark-workers` it will be:

```
export TEMPORAL_TLS_CERT=cluster.pem
export TEMPORAL_TLS_KEY=cluster.key
export TEMPORAL_TLS_CA=ca.cert
```

**Comment by richstokes** [comment]
Thanks. The certs are working! 

I'm confused with the readme though - what is the difference between "worker" and "runner"?

Looks like the worker just schedules tasks in temporal, and the runner then grabs those tasks and executes them. Is that right?

**Comment by robholland** [comment]
The opposite, the worker provides an implementation of a set of Workflows and Activities like your own Temporal workers would do. The runner is responsible for starting and watching workflow executions to keep a constant load level, simulating what your application would do (were it to run at a steady state of load).

**Comment by richstokes** [comment]
Ah. Gotcha. Thanks!
